map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""    # injecté par le launch file
    topic_name: "map"
    frame_id: "map"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false        # Dijkstra: plus stable, paths optimaux
      allow_unknown: false

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.22
      resolution: 0.05
      track_unknown_space: false
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.45    # marge autour des obstacles
      always_send_full_costmap: true

lifecycle_manager_planner:
  ros__parameters:
    use_sim_time: true
    autostart: true
    bond_timeout: 0.0
    node_names: ["map_server", "planner_server"]