<?xml version="1.0"?>
<package format="3">
  <name>pedestrian_manager</name>
  <version>0.1.0</version>
  <description>Gestion Python des pietons dynamiques (PFE LIMO Pro)</description>
  <maintainer email="seryne@estin.dz">Seryne Amrani</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>