global:
  world_name: "hospital"
  update_rate_hz: 30.0
  dynamicity: "medium"
  speed_scale: 1.0
  arrival_tolerance: 0.15

pedestrians:
  - name: "ped_1"
    start: [5.43, 1.62]
    goal:  [2.40, 1.62]
    behavior: "ping_pong"

  - name: "ped_2"
    waypoints:
      - [-3.92, 1.18]
      - [-6.92, 1.18]
      - [-6.92, -1.00]
      - [-3.92, -1.00]
    behavior: "loop"

  - name: "ped_3"
    start: [0.55, -1.96]
    goal:  [2.80, -1.96]
    behavior: "ping_pong"

  - name: "ped_4"
    start: [-6.75, -1.77]
    goal:  [-3.73, -1.77]
    behavior: "ping_pong"

  - name: "ped_5"
    start: [3.21, -6.50]
    goal:  [3.21, -4.14]
    behavior: "ping_pong"

  - name: "ped_6"
    start: [-1.65, -4.20]
    goal:  [-1.65, -6.50]
    behavior: "ping_pong"

  - name: "ped_7"
    start: [3.19, 6.50]
    goal:  [3.19, 4.20]
    behavior: "ping_pong"

  - name: "ped_8"
    start: [-1.76, 4.20]
    goal:  [-1.76, 6.50]
    behavior: "ping_pong"